### ISSUE TITLE
Ant Nebula Issue

### ISSUE THREAD

**Issue by venkatesh27das** [EliverLara/Ant-Nebula#4] opened 2018-09-14 18:16 UTC
I am currently facing issue while opening any folder from VS Code.
Like when you go to file explorer in File->Open Folder and the file explore opens and is blank.
Check out the issue.

**Comment by shahlin** [comment] 2019-02-15 14:37
I'm having the same issue

**Comment by JuanCAlpizar** [comment] 2019-03-26 04:09
![image](https://user-images.githubusercontent.com/2028118/54971099-922b5b80-4f4a-11e9-9b90-6c903e48d5b1.png)
Not sure if the issue has been solved for you guys, but I'm seeing no issue at all with the latest stable version, do you still have the same issue @venkatesh27das  ?

**Comment by shahlin** [comment] 2019-04-01 09:07
@JuanCAlpizar Just checked, the problem is fixed now

**Closed as completed** 2019-10-30 17:33 UTC
